In [32]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [33]:
%reload_ext autoreload

In [1]:
from align import NeedlemanWunsch, read_fasta
import numpy as np

In [2]:
nw = NeedlemanWunsch("./substitution_matrices/BLOSUM62.mat", gap_open = -10, gap_extend = -1)

In [3]:
seq1, _ = read_fasta("./data/test_seq1.fa")
seq2, _ = read_fasta("./data/test_seq2.fa")
seq1, seq2

('MYQR', 'MQR')

In [4]:
print(len(seq1))
print(len(seq2))

4
3


In [ ]:
score, seq1_align, seq2_align = nw.align(seq1, seq2)
print(score)
print(seq1_align)
print(seq2_align)

In [29]:
seq3, _ = read_fasta("./data/test_seq3.fa")
seq4, _ = read_fasta("./data/test_seq4.fa")
seq3, seq4

('MAVHQLIRRP', 'MQLIRHP')

In [31]:
print(len(seq3))
print(len(seq4))

10
7


In [9]:
score, seq3_align, seq4_align = nw.align(seq3, seq4)
print(score)
print(seq3_align)
print(seq4_align)

17.0
-HQLIRRP
M-QLIRHP


In [38]:
align = align_m = np.ones((len(seq3)+1, len(seq4)+1)) * -np.inf
gapA = np.ones((len(seq3)+1, len(seq4)+1)) * -np.inf
gapB = np.ones((len(seq3)+1, len(seq4)+1)) * -np.inf
open_pen = -10
extend_pen=-1

In [39]:
align, gapA, gapB

(array([[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf]]),
 array([[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-in

In [40]:
align[0,0]  = 0
align

array([[  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf]])

In [41]:
for i in range(0, len(seq3)+1): #rows
    gapA[i][0] = open_pen  + (extend_pen*i)
for j in range(0, len(seq4)+1): #columns
    gapB[0][j] = open_pen  + (extend_pen*j)
gapA, gapB

(array([[-10., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-11., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-12., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-13., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-14., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-15., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-16., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-17., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-18., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-19., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-20., -inf, -inf, -inf, -inf, -inf, -inf, -inf]]),
 array([[-10., -11., -12., -13., -14., -15., -16., -17.],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-in

In [99]:
for i in range(1, len(seq3)+1):
    for j in range(1, len(seq4)+1):
        match = nw.sub_dict[(seq3[i-1], seq4[j-1])]
        
        align_vals = [align[i - 1,j - 1],
                      gapA[i - 1, j - 1],
                      gapB[i - 1, j - 1]]
        
        gapA_vals = [open_pen + extend_pen + align[i-1,j],
                      extend_pen + gapA[i - 1, j],
                      extend_pend + open_pen + gapB[i - 1, j]]
        
        gapB_vals = [open_pen + extend_pen + align[i,j-1],
                      extend_pen + gapA[i, j-1],
                      extend_pend + open_pen + gapB[i, j-1]]
        
        align[i,j] = max(align_vals)
        gapA[i,j] = max(gapA_vals)
        gapB[i,j] = max(gapB_vals)
        
        
        

5

In [44]:
print(seq3[i-1])
print(seq4[j-1])
match = nw.sub_dict[(seq3[i-1], seq4[j-1])]
match

P
P


7.0

In [42]:
gapA[::-1]

array([[-20., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-19., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-18., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-17., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-16., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-15., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-14., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-13., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-12., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-11., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-10., -inf, -inf, -inf, -inf, -inf, -inf, -inf]])