In [1]:
from align import NeedlemanWunsch, read_fasta
import numpy as np

In [2]:
nw = NeedlemanWunsch("./substitution_matrices/BLOSUM62.mat", gap_open = -10, gap_extend = -1)

In [3]:
seq1, _ = read_fasta("./data/test_seq1.fa")
seq2, _ = read_fasta("./data/test_seq2.fa")
seq1, seq2

('MYQR', 'MQR')

In [9]:
print(len(seq1))
print(len(seq2))

4
3


In [4]:
score, seq1_align, seq2_align = nw.align(seq1, seq2)
print(score)
print(seq1_align)
print(seq2_align)

4.0
YQR
RQRMRQR


In [88]:
align_m = np.ones((len(seq1)+1, len(seq2)+1)) * -np.inf
align_m

array([[-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [89]:
align_m[0,0] = 0
align_m

array([[  0., -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [90]:
gapA = align_m = np.ones((len(seq1)+1, len(seq2)+1)) * -np.inf
gapB = align_m = np.ones((len(seq1)+1, len(seq2)+1)) * -np.inf

In [91]:
gapA, gapB

(array([[-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf]]),
 array([[-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf]]))

In [92]:
for i in range(0, len(seq1)+1):
    gapA[i][0] = gap_open_penalty  + (gap_extend_penalty*i)
for j in range(0, len(seq2)+1):
    gapB[0][j] = gap_open_penalty  + (gap_extend_penalty*j)
gapA, gapB

(array([[ -1., -inf, -inf, -inf],
        [ -2., -inf, -inf, -inf],
        [ -3., -inf, -inf, -inf],
        [ -4., -inf, -inf, -inf],
        [ -5., -inf, -inf, -inf]]),
 array([[ -1.,  -2.,  -3.,  -4.],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf]]))

In [99]:
x = [3,4,5]
max_x = max(x)
max_x

5

In [100]:
x.index(max_x)

2

In [102]:
gapA[::-1]

array([[ -5., -inf, -inf, -inf],
       [ -4., -inf, -inf, -inf],
       [ -3., -inf, -inf, -inf],
       [ -2., -inf, -inf, -inf],
       [ -1., -inf, -inf, -inf]])